version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python /Scripts/PythonApp.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - PythonApp.py